"""
Demo account seeder for KrishiRakshak.

Run from the backend/ directory:
    python seed_demo.py

What this does:
  1. Creates farmer Ramesh Patil with real farm data (Nashik, Maharashtra)
  2. Seeds 2 farms + 3 crops + 2 financial obligations
  3. Calls the REAL backend API to:
       - Fetch live weather from Open-Meteo for the farm location
       - Trigger the rule engine to generate real advisories
       - Compute real distress score
  All advisories are generated by advisory.py + distress.py — NOTHING is hardcoded.

Credentials:
  Phone:    +919876543210
  Password: demo1234
"""

import sys, os, time
sys.path.insert(0, os.path.dirname(__file__))

import requests
from app.database import SessionLocal
from app import models, auth
from datetime import date, timedelta

BASE_URL     = "http://localhost:8000"
DEMO_PHONE   = "+919876543210"
DEMO_PASSWORD = "demo1234"
DEMO_NAME    = "Ramesh Patil"

db = SessionLocal()

def login_or_register() -> str:
    """Register if not exists, then return JWT token."""
    # Try login first
    resp = requests.post(f"{BASE_URL}/api/v1/auth/login",
                         data={"username": DEMO_PHONE, "password": DEMO_PASSWORD})
    if resp.status_code == 200:
        token = resp.json()["access_token"]
        print(f"[seed] Logged in as {DEMO_PHONE}")
        return token

    # Register
    resp = requests.post(f"{BASE_URL}/api/v1/auth/register", json={
        "name": DEMO_NAME,
        "phone": DEMO_PHONE,
        "password": DEMO_PASSWORD,
        "language": "marathi",
        "location_id": "Nashik_Maharashtra",
    })
    if resp.status_code not in (200, 201):
        raise RuntimeError(f"Registration failed: {resp.status_code} {resp.text}")

    # Now login
    resp = requests.post(f"{BASE_URL}/api/v1/auth/login",
                         data={"username": DEMO_PHONE, "password": DEMO_PASSWORD})
    token = resp.json()["access_token"]
    print(f"[seed] Registered + logged in as {DEMO_PHONE}")
    return token


def headers(token: str) -> dict:
    return {"Authorization": f"Bearer {token}"}


def run():
    # ── 0. Get token ────────────────────────────────────────────────────────
    token = login_or_register()
    h = headers(token)

    # ── 1. Get farmer from DB to clear old seeded data ───────────────────
    farmer = db.query(models.Farmer).filter(models.Farmer.phone == DEMO_PHONE).first()
    if farmer:
        for farm in db.query(models.Farm).filter(models.Farm.farmer_id == farmer.id).all():
            db.query(models.Advisory).filter(models.Advisory.farm_id == farm.id).delete()
            db.query(models.Crop).filter(models.Crop.farm_id == farm.id).delete()
        db.query(models.Alert).filter(models.Alert.farmer_id == farmer.id).delete()
        db.query(models.FinancialObligation).filter(models.FinancialObligation.farmer_id == farmer.id).delete()
        db.query(models.DistressScore).filter(models.DistressScore.farmer_id == farmer.id).delete()
        db.query(models.Farm).filter(models.Farm.farmer_id == farmer.id).delete()
        db.commit()
        print(f"[seed] Cleared old data for farmer id={farmer.id}")

    # ── 2. Add farms via API ─────────────────────────────────────────────
    farm1_resp = requests.post(f"{BASE_URL}/api/v1/farmers/me/farms", headers=h, json={
        "name": "Nashik Main Farm",
        "area": 3.5,
        "soil_type": "loam",
        "irrigation": "drip",
        "latitude": 20.0059,
        "longitude": 73.7898,
        "state": "Maharashtra",
        "district": "Nashik",
    })
    if farm1_resp.status_code not in (200, 201):
        raise RuntimeError(f"Farm1 creation failed: {farm1_resp.text}")
    farm1_id = farm1_resp.json()["id"]
    print(f"[seed] Farm 1 created: Nashik Main Farm (id={farm1_id})")

    farm2_resp = requests.post(f"{BASE_URL}/api/v1/farmers/me/farms", headers=h, json={
        "name": "Pimpalgaon Plot",
        "area": 1.8,
        "soil_type": "black",
        "irrigation": "sprinkler",
        "latitude": 20.1234,
        "longitude": 74.0987,
        "state": "Maharashtra",
        "district": "Nashik",
    })
    if farm2_resp.status_code not in (200, 201):
        raise RuntimeError(f"Farm2 creation failed: {farm2_resp.text}")
    farm2_id = farm2_resp.json()["id"]
    print(f"[seed] Farm 2 created: Pimpalgaon Plot (id={farm2_id})")

    # ── 3. Add crops via API ─────────────────────────────────────────────
    today = date.today()

    crops = [
        {
            "farm_id": farm1_id,
            "crop_type": "tomato",
            "variety": "Namdhari NS-585",
            "sowing_date": str(today - timedelta(days=52)),
            "stage": "Fruit Development",
            "expected_harvest_date": str(today + timedelta(days=28)),
            "image_url": "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop",
        },
        {
            "farm_id": farm1_id,
            "crop_type": "onion",
            "variety": "Nasik Red",
            "sowing_date": str(today - timedelta(days=35)),
            "stage": "Vegetative Growth",
            "expected_harvest_date": str(today + timedelta(days=60)),
            "image_url": "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=600&auto=format&fit=crop",
        },
        {
            "farm_id": farm2_id,
            "crop_type": "wheat",
            "variety": "HD-2967",
            "sowing_date": str(today - timedelta(days=20)),
            "stage": "Germination",
            "expected_harvest_date": str(today + timedelta(days=100)),
            "image_url": "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&auto=format&fit=crop",
        },
    ]
    crop_ids = []
    for c in crops:
        farm_id = c.pop("farm_id")
        r = requests.post(f"{BASE_URL}/api/v1/farms/{farm_id}/crops", headers=h, json=c)
        if r.status_code not in (200, 201):
            print(f"  [warn] Crop creation warning: {r.status_code} {r.text}")
        else:
            crop_ids.append(r.json()["id"])
            print(f"[seed] Crop created: {c['crop_type']} (id={r.json()['id']})")

    # ── 4. Add financial obligations via API ─────────────────────────────
    obs = [
        {"amount": 45000.0, "due_date": str(today + timedelta(days=18)), "type": "loan",   "description": "KCC loan repayment"},
        {"amount": 12000.0, "due_date": str(today + timedelta(days=5)),  "type": "inputs", "description": "Pesticide + fertiliser input credit"},
    ]
    for ob in obs:
        r = requests.post(f"{BASE_URL}/api/v1/farmers/me/obligations", headers=h, json=ob)
        if r.status_code not in (200, 201):
            print(f"  [warn] Obligation warning: {r.status_code} {r.text}")
        else:
            print(f"[seed] Obligation: ₹{ob['amount']:,.0f} {ob['type']} (due {ob['due_date']})")

    # ── 5. Update farmer language + location ─────────────────────────────
    r = requests.put(f"{BASE_URL}/api/v1/farmers/me", headers=h, json={
        "language": "marathi",
        "location_id": "Nashik_Maharashtra",
        "risk_profile": "Elevated",
    })
    if r.status_code in (200, 201, 204):
        print("[seed] Farmer profile updated (language=marathi, location=Nashik)")

    # ── 6. Trigger REAL weather fetch (Open-Meteo) ────────────────────────
    # This fetches actual weather for Nashik farm GPS coords
    print("\n[seed] Fetching REAL weather from Open-Meteo for Nashik (lat=20.0059, lon=73.7898)...")
    r = requests.post(f"{BASE_URL}/api/v1/weather/Nashik_Maharashtra/refresh", headers=h)
    if r.status_code in (200, 201):
        print("[seed] ✅ Weather data fetched from Open-Meteo!")
    else:
        print(f"[seed] ⚠️  Weather fetch returned {r.status_code}: {r.text[:200]}")

    # Step 7: GET advisories — this auto-runs evaluate_advisories() rule engine
    print("[seed] Triggering REAL advisory engine (GET /api/v1/advisories)...")
    r = requests.get(f"{BASE_URL}/api/v1/advisories", headers=h)
    if r.status_code == 200:
        advs = r.json()
        print(f"[seed] ✅ {len(advs)} advisories generated by rule engine!")
        for a in advs:
            print(f"       [{a.get('priority','?').upper()}] {a.get('category','?')}: {a.get('recommendation','')[:80]}...")
    else:
        print(f"[seed] ⚠️  Advisory endpoint returned {r.status_code}: {r.text[:200]}")

    # Step 8: Compute REAL distress score
    print("[seed] Computing REAL distress score...")
    r = requests.get(f"{BASE_URL}/api/v1/farmers/me/distress", headers=h)
    if r.status_code == 200:
        ds = r.json()
        print(f"[seed] ✅ Distress: {ds.get('score', '?')}/100 ({ds.get('risk_level', '?')})")
        print(f"       weather={ds.get('weather_component','?')}, market={ds.get('market_component','?')}, yield={ds.get('yield_component','?')}")
    else:
        print(f"[seed] ⚠️  Distress returned {r.status_code}: {r.text[:200]}")

    # ── 9. Summary ────────────────────────────────────────────────────────
    print("\n" + "="*62)
    print("✅  DEMO ACCOUNT READY — all data is REAL (engine-generated)")
    print("="*62)
    print(f"  📱  Phone:     {DEMO_PHONE}")
    print(f"  🔑  Password:  {DEMO_PASSWORD}")
    print(f"  👤  Name:      {DEMO_NAME} (language: Marathi)")
    print(f"  🌾  Farm 1:    Nashik Main Farm — 3.5 acres (loam, drip)")
    print(f"  🌾  Farm 2:    Pimpalgaon Plot  — 1.8 acres (black cotton, sprinkler)")
    print(f"  🍅  Crop 1:    Tomato (Namdhari NS-585) — 52 days old, Fruit Development")
    print(f"  🧅  Crop 2:    Onion (Nasik Red)         — 35 days old, Vegetative Growth")
    print(f"  🌾  Crop 3:    Wheat (HD-2967)            — 20 days old, Germination")
    print(f"  💰  Loan:      ₹45,000 KCC repayment due in 18 days")
    print(f"  💰  Inputs:    ₹12,000 input credit due in 5 days")
    print(f"  🌦️   Weather:   LIVE from Open-Meteo (Nashik GPS)")
    print(f"  ⚠️   Advisories: REAL — generated by rule engine based on actual weather")
    print(f"  📊  Distress:  REAL — computed from weather, yield, market, financial data")
    print("="*62)
    print("  👉  Open http://localhost:5173 and log in with above creds")
    print("="*62 + "\n")


if __name__ == "__main__":
    try:
        run()
    finally:
        db.close()
